# Copyright 2019 the Tectonic Project
# Licensed under the MIT License.

# Environment variables:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

trigger:
  branches:
    exclude:
    - '*'

pr:
- master

jobs:
- template: .azure-pipelines/qemu-chroot.yml
  parameters:
    buildenv_name: ppc
