[build.env]
passthrough = [
  "PKG_CONFIG_ALLOW_CROSS",
  "PKG_CONFIG_LIBDIR",
  "RUST_BACKTRACE",
  "RUST_LOG",
  "RUSTFLAGS",
  "TECTONIC_DEP_BACKEND",
  "VCPKG_ROOT",
]

[target.aarch64-unknown-linux-gnu]
image = "local:aarch64-unknown-linux-gnu"
