[build.env]
passthrough = [
  "PKG_CONFIG_ALLOW_CROSS",
  "RUST_BACKTRACE",
  "RUST_LOG",
  "RUSTFLAGS",
  "TECTONIC_DEP_BACKEND",
  "VCPKG_ROOT",
]

[target.i586-unknown-linux-musl]
image = "local:i586-unknown-linux-musl"
