language = "C"
cpp_compat = true
style = "type"
include_guard = "TECTONIC_ENGINE_XETEX_BINDGEN_H"

[export.rename]
"CoreBridgeState" = "ttbc_state_t"
"Diagnostic" = "ttbc_diagnostic_t"
"FileFormat" = "ttbc_file_format"

[export]
exclude = ["Option_OutputId", "Option_InputId"]

[enum]
prefix_with_name = true
