[target.aarch64-unknown-linux-musl]
image = "tectonictypesetting/crossbuild:aarch64-unknown-linux-musl"

[target.arm-unknown-linux-musleabihf]
image = "tectonictypesetting/crossbuild:arm-unknown-linux-musleabihf"

[target.i686-unknown-linux-gnu]
image = "tectonictypesetting/crossbuild:i686-unknown-linux-gnu"

[target.mips-unknown-linux-gnu]
image = "tectonictypesetting/crossbuild:mips-unknown-linux-gnu"

[target.x86_64-unknown-linux-musl]
image = "tectonictypesetting/crossbuild:x86_64-unknown-linux-musl"
