/* lib.h: declare prototypes for functions in lib.a.
  Public domain. */

#ifndef LIB_LIB_H
#define LIB_LIB_H

/* main.c (or win32main.c or texmfmp.c) */
#ifndef NOT_WEB2C
/* Only used in Web2C programs and possibly harmful otherwise.  */
extern int argc;
extern string *argv;
extern string cmdline (int);
extern void main_body (void); /* generated by web2c */
#endif

/* openclose.c */
extern boolean open_input (FILE **, int, const_string fopen_mode);
extern boolean open_output (FILE **, const_string fopen_mode);
extern void close_file (FILE *);

extern string fullnameoffile;

/* printversion.c */
extern void printversionandexit (const_string, const_string, const_string, const_string);

/* usage.c */
extern void usagehelp (const_string *message, const_string bug_email);

/* version.c */
extern const char *version_string;

/* zround.c */
extern integer zround (double);

#endif /* not LIB_LIB_H */
