# Copyright 2020-2021 the Tectonic Project
# Licensed under the MIT License.

# See README.md for discussion of features (or lack thereof) in this crate.

[package]
name = "tectonic_xetex_layout"
version = "0.0.0-dev.0" # assigned with cranko (see README)
authors = ["Peter Williams <peter@newton.cx>"]
description = """
XeTeX's font loading and layout interface encapsulation, as a crate.
"""
homepage = "https://tectonic-typesetting.github.io/"
documentation = "https://docs.rs/tectonic_xetex_layout"
repository = "https://github.com/tectonic-typesetting/tectonic/"
readme = "README.md"
license = "MIT"
edition = "2018"
links = "tectonic_xetex_layout"

[dependencies]
tectonic_bridge_core = { path = "../bridge_core", version = "0.0.0-dev.0" }
tectonic_bridge_freetype2 = { path = "../bridge_freetype2", version = "0.0.0-dev.0" }
tectonic_bridge_graphite2 = { path = "../bridge_graphite2", version = "0.0.0-dev.0" }
tectonic_bridge_harfbuzz = { path = "../bridge_harfbuzz", version = "0.0.0-dev.0" }
tectonic_bridge_icu = { path = "../bridge_icu", version = "0.0.0-dev.0" }
tectonic_io_base = { path = "../io_base", version = "0.0.0-dev.0" }
libc = "0.2"

[build-dependencies]
cc = "^1.0.66"
tectonic_cfg_support = { path = "../cfg_support", version = "0.0.0-dev.0" }
tectonic_dep_support = { path = "../dep_support", version = "0.0.0-dev.0" }
os_info = "3"

[features]
external-harfbuzz = ["tectonic_bridge_harfbuzz/external-harfbuzz"]

[package.metadata.internal_dep_versions]
tectonic_bridge_core = "thiscommit:2021-01-16:wie2Ejoh"
tectonic_bridge_graphite2 = "2722731f9e32c6963fe8c8566a201b33672c5c5a"
tectonic_bridge_freetype2 = "2c1ffcd702a662c003bd3d7d0ca4d169784cb6ad"
tectonic_bridge_harfbuzz = "2c1ffcd702a662c003bd3d7d0ca4d169784cb6ad"
tectonic_bridge_icu = "thiscommit:2023-09-17:6uIZ4lA"
tectonic_cfg_support = "thiscommit:aeRoo7oa"
tectonic_dep_support = "5faf4205bdd3d31101b749fc32857dd746f9e5bc"
tectonic_io_base = "41168a9fa2902401afc79e60bbefa638bde6df2d"
