language = "C"
cpp_compat = true
style = "type"
include_guard = "XETEX_LAYOUT_BINDINGS_H"
includes = ["harfbuzz/hb.h", "harfbuzz/hb-ft.h", "fontconfig/fontconfig.h"]
after_includes = "typedef struct XeTeXFont_rec* XeTeXFont;"

[export.rename]

[enum]
prefix_with_name = true
