language = "C"
cpp_compat = true
style = "type"
include_guard = "TECTONIC_BRIDGE_CORE_GENERATED_H"
after_includes = """
typedef struct ttbc_input_handle_t ttbc_input_handle_t;
typedef struct ttbc_output_handle_t ttbc_output_handle_t;
typedef ttbc_input_handle_t *rust_input_handle_t;
typedef ttbc_output_handle_t *rust_output_handle_t;
"""

[enum]
prefix_with_name = true

[export.rename]
"CoreBridgeState" = "ttbc_state_t"
"Diagnostic" = "ttbc_diagnostic_t"
"FileFormat" = "ttbc_file_format"
"InputHandle" = "ttbc_input_handle_t"
"OutputHandle" = "ttbc_output_handle_t"