name: "Push CI/CD"

on:
  push:
    branches: [ master, rc ]

jobs:
  prep:
    uses: ./.github/workflows/prep.yml
  build_and_test:
    needs: prep
    uses: ./.github/workflows/build_and_test.yml
    secrets: inherit
  deploy:
    needs: build_and_test
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/deploy.yml
    with:
      is-dev: ${{ github.ref_name == 'master' }}
      is-release: ${{ github.ref_name == 'rc' }}
    secrets: inherit
