name: "Tectonic on arXiv"

on:
  pull_request:

jobs:
  tectonic-on-arxiv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up s3
        uses: s3-actions/s3cmd@v3.0.0
        with:
          provider: cloudflare
          access_key: ${{ secrets.CLOUDFLARE_ACCESS_KEY }}
          secret_key: ${{ secrets.CLOUDFLARE_SECRET_KEY }}
          account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      - name: Load Dataset
        run: |
          s3cmd get "$CLOUDFLARE_URL/1702.tar.gz" 1702.tar.gz
          mkdir datasets
          tar -xzvf 1702.tar.gz -C datasets
        env:
          CLOUDFLARE_URL: ${{ vars.CLOUDFLARE_URL }}
      - name: Tectonic-on-ArXiv
        uses: craftspider/tectonic-on-arxiv@master