name: "Tectonic on arXiv"

on: [ workflow_call ]

jobs:
  tectonic-on-arxiv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Tectonic-on-ArXiv
        uses: craftspider/tectonic-on-arxiv@master